package com.flowsense.webhook;

import com.flowsense.prediction.PRImpactReport;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.Map;

/**
 * Posts FlowSense analysis as a comment on GitHub PRs.
 *
 * INTERVIEW TALKING POINT:
 * "The comment is formatted as a Markdown table so it's immediately
 * readable in the GitHub PR UI. I format the risk score with a
 * color emoji so engineers can see criticality at a glance without
 * reading the full comment."
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class PRCommentPublisher {

    private final RestTemplate restTemplate;

    @Value("${flowsense.github.token:}")
    private String githubToken;

    /**
     * Post the impact analysis as a PR comment.
     */
    public void postAnalysisComment(PREvent event, PRImpactReport report) {
        if (githubToken == null || githubToken.isBlank()) {
            log.warn("GitHub token not configured — skipping comment post");
            log.info("Analysis for PR #{}: risk={}", event.getPrNumber(), report.getRiskScore());
            return;
        }

        String commentBody = formatComment(report);
        String apiUrl = "https://api.github.com/repos/" +
                event.getRepoName() + "/issues/" + event.getPrNumber() + "/comments";

        try {
            HttpHeaders headers = new HttpHeaders();
            headers.setBearerAuth(githubToken);
            headers.setContentType(MediaType.APPLICATION_JSON);

            HttpEntity<Map<String, String>> request = new HttpEntity<>(
                    Map.of("body", commentBody), headers);

            ResponseEntity<String> response = restTemplate.postForEntity(
                    apiUrl, request, String.class);

            if (response.getStatusCode().is2xxSuccessful()) {
                log.info("✅ Posted analysis comment to PR #{}", event.getPrNumber());
            } else {
                log.warn("GitHub API returned: {}", response.getStatusCode());
            }

        } catch (Exception e) {
            log.error("Failed to post GitHub comment: {}", e.getMessage());
        }
    }

    /**
     * Format the analysis as a beautiful Markdown comment.
     */
    private String formatComment(PRImpactReport report) {
        String riskEmoji = switch (report.getRiskLevel()) {
            case "CRITICAL" -> "🔴";
            case "HIGH" -> "🟠";
            case "MEDIUM" -> "🟡";
            default -> "🟢";
        };

        StringBuilder sb = new StringBuilder();

        sb.append("## ").append(riskEmoji)
                .append(" FlowSense Impact Analysis — Risk Score: **")
                .append(report.getRiskScore()).append("/100** (")
                .append(report.getRiskLevel()).append(")\n\n");

        // Risk explanation
        sb.append("### 🧠 Analysis\n");
        sb.append(report.getRiskExplanation()).append("\n\n");

        // Impact table
        sb.append("### 📊 Impact Breakdown\n\n");
        sb.append("| Signal | Value |\n");
        sb.append("|--------|-------|\n");
        sb.append("| Changed Classes | `")
                .append(String.join("`, `", report.getChangedClasses())).append("` |\n");
        sb.append("| Directly Impacted Services | ")
                .append(report.getDirectlyImpactedServices().size()).append(" |\n");
        sb.append("| Transitively Impacted | ")
                .append(report.getTransitivelyImpactedServices().size()).append(" |\n");
        sb.append("| Historical Risk Signal | ")
                .append(String.format("%.0f%%", report.getHistoricalRiskSignal() * 100)).append(" |\n");
        sb.append("| Complexity Risk Signal | ")
                .append(String.format("%.0f%%", report.getComplexityRiskSignal() * 100)).append(" |\n\n");

        // Impacted services
        if (!report.getDirectlyImpactedServices().isEmpty()) {
            sb.append("### ⚠️ Directly Impacted Services\n");
            report.getDirectlyImpactedServices()
                    .forEach(svc -> sb.append("- `").append(svc).append("`\n"));
            sb.append("\n");
        }

        // Recommended tests
        sb.append("### 🧪 Recommended Tests\n");
        report.getRecommendedTests()
                .forEach(test -> sb.append("- [ ] ").append(test).append("\n"));
        sb.append("\n");

        sb.append("---\n");
        sb.append("*Generated by [FlowSense Pro](https://github.com/you/flowsense-pro) ")
                .append("at ").append(report.getAnalyzedAt()).append("*");

        return sb.toString();
    }
}
