package com.flowsense.documentation;

import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Complete documentation for an entire project.
 */
@Data
@Builder
public class ProjectDocs {

    private String projectId;
    private List<ServiceDoc> serviceDocs;
    private int totalServices;
    private int servicesWithDrift;
    private int totalDriftIssues;
    private double avgOnboardingDays;
    private LocalDateTime generatedAt;

    /**
     * Export full project docs as a single Markdown file.
     * Can be committed to the repo as CODEBASE.md
     */
    public String toMarkdown() {
        StringBuilder md = new StringBuilder();

        md.append("# ").append(projectId).append(" — Codebase Documentation\n\n");
        md.append("> Auto-generated by FlowSense Pro at ")
                .append(generatedAt).append("\n\n");

        md.append("## Project Overview\n\n");
        md.append("| Metric | Value |\n|--------|-------|\n");
        md.append("| Total Services | ").append(totalServices).append(" |\n");
        md.append("| Services With Doc Drift | ").append(servicesWithDrift).append(" |\n");
        md.append("| Total Drift Issues | ").append(totalDriftIssues).append(" |\n");
        md.append("| Avg Onboarding Time | ")
                .append(String.format("%.1f", avgOnboardingDays)).append(" days |\n\n");

        md.append("## Table of Contents\n\n");
        serviceDocs.forEach(doc -> md.append("- [").append(doc.getClassName()).append("](#")
                .append(doc.getClassName().toLowerCase()).append(")\n"));
        md.append("\n---\n\n");

        // Individual service docs
        serviceDocs.forEach(doc -> {
            md.append(doc.toMarkdown());
            md.append("\n---\n\n");
        });

        return md.toString();
    }

    /**
     * Get only services with drift issues — for a quick report.
     */
    public List<ServiceDoc> getServicesWithDrift() {
        return serviceDocs.stream()
                .filter(ServiceDoc::isHasDrift)
                .collect(Collectors.toList());
    }
}
