package com.flowsense.documentation;

import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.Collections;
import java.util.List;

/**
 * Complete documentation for a single Java class/service.
 * Can be exported to Markdown, Confluence, or HTML.
 */
@Data
@Builder
public class ServiceDoc {

    private String className;
    private String fullyQualifiedName;
    private String filePath;
    private String classType;
    private String projectId;

    // LLM-generated prose sections
    private String overview; // 2-3 sentence summary
    private String responsibilities; // Bullet list of what it does
    private String integrationGuide; // How to use this class
    private String onboardingNotes; // Advice for new engineers

    // Structural facts from graph
    private List<String> publicMethods;
    private List<String> directDependencies;
    private List<String> usedBy;
    private String mermaidDiagram; // Auto-generated dependency diagram

    // Doc drift detection
    private List<DocDriftDetector.DriftIssue> driftIssues;
    private boolean hasDrift;

    // Metrics
    private int estimatedOnboardingDays;
    private int totalMethods;
    private int publicMethodCount;
    private double avgComplexity;

    private LocalDateTime generatedAt;
    private long generationMs;
    private boolean found;

    public static ServiceDoc notFound(String className) {
        return ServiceDoc.builder()
                .className(className)
                .found(false)
                .overview("Class not found in the indexed codebase.")
                .driftIssues(Collections.emptyList())
                .publicMethods(Collections.emptyList())
                .directDependencies(Collections.emptyList())
                .usedBy(Collections.emptyList())
                .build();
    }

    /**
     * Export as clean Markdown — for README, Confluence, Notion.
     */
    public String toMarkdown() {
        StringBuilder md = new StringBuilder();

        md.append("# ").append(className).append("\n\n");
        md.append("> `").append(fullyQualifiedName).append("`\n\n");

        md.append("## Overview\n\n");
        md.append(overview).append("\n\n");

        md.append("## Responsibilities\n\n");
        md.append(responsibilities).append("\n\n");

        if (!usedBy.isEmpty()) {
            md.append("## Used By\n\n");
            usedBy.forEach(u -> md.append("- `").append(u).append("`\n"));
            md.append("\n");
        }

        if (!publicMethods.isEmpty()) {
            md.append("## Public API\n\n");
            publicMethods.forEach(m -> md.append("- `").append(m).append("`\n"));
            md.append("\n");
        }

        md.append("## Architecture\n\n");
        md.append(mermaidDiagram != null ? mermaidDiagram : "_No diagram available_").append("\n\n");

        md.append("## Integration Guide\n\n");
        md.append(integrationGuide).append("\n\n");

        md.append("## Onboarding Notes\n\n");
        md.append(onboardingNotes).append("\n\n");

        md.append("## Metrics\n\n");
        md.append("| Metric | Value |\n|--------|-------|\n");
        md.append("| Total Methods | ").append(totalMethods).append(" |\n");
        md.append("| Public Methods | ").append(publicMethodCount).append(" |\n");
        md.append("| Avg Complexity | ").append(String.format("%.1f", avgComplexity)).append(" |\n");
        md.append("| Estimated Onboarding | ").append(estimatedOnboardingDays).append(" days |\n\n");

        if (hasDrift && driftIssues != null && !driftIssues.isEmpty()) {
            md.append("## ⚠️ Documentation Drift Detected\n\n");
            driftIssues.forEach(issue -> {
                md.append("- **[Line ").append(issue.getLineNumber()).append("]** ")
                        .append(issue.getDescription()).append("\n");
            });
            md.append("\n");
        }

        md.append("---\n");
        md.append("*Generated by FlowSense Pro at ").append(generatedAt).append("*\n");

        return md.toString();
    }
}
